# Generated by Django 5.2.3 on 2025-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('CL', 'Clothing'), ('FD', 'Food'), ('FR', 'Furniture'), ('BK', 'Books'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Product Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
