# Generated by Django 5.2.3 on 2025-06-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Cereals'), ('VE', 'Vegatables'), ('FD', 'Food'), ('FR', 'Fruits'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Product Category'),
        ),
    ]
